# https://docs.docker.com/build/ci/github-actions/examples/
name: CI

on:
  schedule:
    - cron: "0 10 * * *"
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"
  release:
    types:
      - published

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
env:
  IMAGE_NAME: "my-image"
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
      issues: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Lint Dockerfile
        uses: hadolint/hadolint-action@v3.1.0
        with:
          failure-threshold: error

      - name: Build
        uses: docker/build-push-action@v4
        with:
          context: .
          load: true
          push: false
          tags: ${{env.IMAGE_NAME}}:${{ github.sha }}

      - name: Setup container structure tests
        run: |
          curl -fsLO https://storage.googleapis.com/container-structure-test/v1.14.0/container-structure-test-linux-amd64
          chmod +x container-structure-test-linux-amd64
          sudo mv container-structure-test-linux-amd64 /usr/local/bin/container-structure-test
          container-structure-test version

      - name: Run tests
        run: |
          container-structure-test test --image ${{env.IMAGE_NAME}}:${{ github.sha }} --config structure-tests.yaml

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: |
            ghcr.io/${{ github.repository }}
          tags: |
            type=schedule
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=sha
          labels: |
            org.opencontainers.image.title=Demo image
            org.opencontainers.image.description=Image Description
            org.opencontainers.image.vendor=ExodiaLabs

      - name: Login to GHCR
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push to registry
        uses: docker/build-push-action@v4
        if: github.event_name != 'pull_request'
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
